package org.reactome.server.tools.interactors.util;

/**
 * @author Guilherme S Viteri <gviteri@ebi.ac.uk>
 */

public class QueryStatement {

    /** CREATE TABLE STATEMENTS **/
    public static String CREATE_TABLE_INTERACTOR_RESOURCE = "CREATE TABLE INTERACTOR_RESOURCE (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR NOT NULL, URL VARCHAR NOT NULL)";
    public static String CREATE_TABLE_INTERACTION_RESOURCE = "CREATE TABLE INTERACTION_RESOURCE (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR NOT NULL, URL VARCHAR)";

    public static String CREATE_TABLE_INTERACTOR = "CREATE TABLE INTERACTOR (ID INTEGER PRIMARY KEY AUTOINCREMENT, ACC VARCHAR NOT NULL, INTERACTOR_RESOURCE_ID INTEGER NOT NULL)";
    public static String CREATE_TABLE_INTERACTION = "CREATE TABLE INTERACTION (ID INTEGER PRIMARY KEY AUTOINCREMENT, INTERACTOR_A INTEGER NOT NULL, INTERACTOR_B INTEGER NOT NULL, INTERACTION_ID VARCHAR, AUTHOR_SCORE NUMERIC, MISCORE NUMERIC, INTERACTION_RESOURCE_ID VARCHAR)";


    /** INSERT **/
    public static String INSERT_INTERACTOR_RESOURCE_UNIPROT = "INSERT OR REPLACE INTO INTERACTOR_RESOURCE (NAME, URL) VALUES ('UniProt','http://www.uniprot.org/uniprot/##ID##')";
    public static String INSERT_INTERACTOR_RESOURCE_CHEBI = "INSERT OR REPLACE INTO INTERACTOR_RESOURCE (NAME, URL) VALUES ('ChEBI','https://www.ebi.ac.uk/chebi/searchId.do?chebiId=##ID##')";

    public static String INSERT_INTERACTION_RESOURCE_INTACT = "INSERT OR REPLACE INTO INTERACTION_RESOURCE (NAME, URL) VALUES ('IntAct','http://www.ebi.ac.uk/intact/interaction/##ID##')";

    /** CREATE INDEX STATEMENTS **/


    /** CREATE FOREIGN KEYS RELATIONSHIP **/


    /** CREATE FURTHER VALIDATION CONSTRAINTS **/


}
