/** CREATE TABLE STATEMENTS **/
CREATE TABLE INTERACTOR_RESOURCE (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR NOT NULL,
  URL  VARCHAR NOT NULL
);

CREATE TABLE INTERACTION_RESOURCE (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR NOT NULL,
  URL  VARCHAR
);

CREATE TABLE INTERACTOR (
  ID                     INTEGER PRIMARY KEY AUTOINCREMENT,
  ACC                    VARCHAR NOT NULL,
  INTACT_ID              VARCHAR,
  INTERACTOR_RESOURCE_ID INTEGER NOT NULL,
  CREATE_DATE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (INTERACTOR_RESOURCE_ID) REFERENCES INTERACTOR_RESOURCE (ID)
);

CREATE TABLE INTERACTION (
  ID                      INTEGER PRIMARY KEY AUTOINCREMENT,
  INTERACTOR_A            INTEGER NOT NULL,
  INTERACTOR_B            INTEGER NOT NULL,
  AUTHOR_SCORE            NUMERIC,
  MISCORE                 NUMERIC,
  INTERACTION_RESOURCE_ID VARCHAR,
  FOREIGN KEY (INTERACTOR_A) REFERENCES INTERACTOR (ID),
  FOREIGN KEY (INTERACTOR_B) REFERENCES INTERACTOR (ID),
  FOREIGN KEY (INTERACTION_RESOURCE_ID) REFERENCES INTERACTION_RESOURCE (ID)
);

CREATE TABLE INTERACTION_DETAILS (
  ID             INTEGER PRIMARY KEY AUTOINCREMENT,
  INTERACTION_ID INTEGER,
  INTERACTION_AC VARCHAR NOT NULL,
  FOREIGN KEY (INTERACTION_ID) REFERENCES INTERACTION (ID)
);

/** INSERT **/
INSERT OR REPLACE INTO INTERACTOR_RESOURCE (NAME, URL) VALUES ('UniProt', 'http://www.uniprot.org/uniprot/##ID##');

INSERT OR REPLACE INTO INTERACTOR_RESOURCE (NAME, URL)
VALUES ('ChEBI', 'https://www.ebi.ac.uk/chebi/searchId.do?chebiId=##ID##');

INSERT OR REPLACE INTO INTERACTION_RESOURCE (NAME, URL)
VALUES ('IntAct', 'http://www.ebi.ac.uk/intact/interaction/##ID##');